// File generated by flutterfire configure
// This is a placeholder configuration. Run `flutterfire configure` to generate proper values.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC5HLAKyXFq1RtFvxZ6ZOmWGGZVReJo_0',
    appId: '1:256096941502:web:63570675d0910675caf5ef',
    messagingSenderId: '256096941502',
    projectId: 'ems-app-design',
    authDomain: 'ems-app-design.firebaseapp.com',
    storageBucket: 'ems-app-design.firebasestorage.app',
    measurementId: 'G-3CG9Q1JCGN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnTxr3BJAmvPJUVvl_lxMvB9gXNvoQCF0',
    appId: '1:256096941502:android:ef58c7ee6bc93ed8caf5ef',
    messagingSenderId: '256096941502',
    projectId: 'ems-app-design',
    storageBucket: 'ems-app-design.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAB9frxscd6pXlKlAYertilm5fSTGBTiU',
    appId: '1:256096941502:ios:c2e0d2a1c79c802fcaf5ef',
    messagingSenderId: '256096941502',
    projectId: 'ems-app-design',
    storageBucket: 'ems-app-design.firebasestorage.app',
    iosClientId: '256096941502-06ke6scfjevr1drf7mn9k1j0isiauucc.apps.googleusercontent.com',
    iosBundleId: 'com.example.mediride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAB9frxscd6pXlKlAYertilm5fSTGBTiU',
    appId: '1:256096941502:ios:c2e0d2a1c79c802fcaf5ef',
    messagingSenderId: '256096941502',
    projectId: 'ems-app-design',
    storageBucket: 'ems-app-design.firebasestorage.app',
    iosClientId: '256096941502-06ke6scfjevr1drf7mn9k1j0isiauucc.apps.googleusercontent.com',
    iosBundleId: 'com.example.mediride',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC5HLAKyXFq1RtFvxZ6ZOmWGGZVReJo_0',
    appId: '1:256096941502:web:0b996b31a286a724caf5ef',
    messagingSenderId: '256096941502',
    projectId: 'ems-app-design',
    authDomain: 'ems-app-design.firebaseapp.com',
    storageBucket: 'ems-app-design.firebasestorage.app',
    measurementId: 'G-FKQKFSKQHE',
  );

}